### ISSUE TITLE
什么时候支持dubbo 3

### ISSUE THREAD

**Issue by wolfewf** [polarismesh/dubbo-java-polaris#21]
什么时候支持dubbo 3

**Comment by GMY-i** [comment]
什么时候支持dubbo3

**Comment by chuntaojun** [comment]
> 什么时候支持dubbo3

北极星的服务契约还在开发中，等这个服务端 ready 之后就可以正式接入 dubbo3 的应用级注册发现

**Comment by Guan-Meng-Yuan** [comment]
这个iussue创建于2022年，已经2024年了，想问下支持dubbo3了吗

**Comment by chuntaojun** [comment]
下周会开发完毕，年前可以体验
